---
title: Pokémon Statistics
author: Aaron Lang
output:
  html_document:
    code_folding: hide
    df_print: kable
    toc: yes
    toc_float: true
  html_notebook:
    code_folding: hide
    toc: yes
    toc_float: true
---

```{r include=FALSE}
library(dplyr)
library(ggplot2)
pokemon <- read.csv(file = "pokemon.csv")
```

# Height

```{r}
summary(pokemon$height_m)
```
```{r}
pokemon %>% arrange(height_m) %>% head %>% select(generation, pokedex_number, name, height_m)
pokemon %>% arrange(-height_m) %>% head %>% select(generation, pokedex_number, name, height_m)
```
```{r}
ggplot(pokemon, aes(height_m)) + geom_density() + scale_x_log10()
```


# Weight

```{r}
summary(pokemon$weight_kg)
```
```{r}
pokemon %>% arrange(weight_kg) %>% head %>% select(generation, pokedex_number, name, weight_kg)
pokemon %>% arrange(-weight_kg) %>% head %>% select(generation, pokedex_number, name, weight_kg)
```
```{r}
ggplot(pokemon, aes(weight_kg)) + geom_density() + scale_x_log10()
```

# Density

```{r}
pokemon <- pokemon %>% mutate(density = weight_kg/height_m)
summary(pokemon$density)
```
```{r}
pokemon %>% arrange(density) %>% head %>% select(generation, pokedex_number, name, density)
pokemon %>% arrange(-density) %>% head %>% select(generation, pokedex_number, name, density)
```
```{r}
ggplot(pokemon, aes(density)) + geom_density() + scale_x_log10()
```

# Body Mass Index (BMI)

```{r}
pokemon <- pokemon %>% mutate(bmi = weight_kg/(height_m^2))
summary(pokemon$bmi)
```
```{r}
pokemon %>% arrange(bmi) %>% head %>% select(generation, pokedex_number, name, bmi)
pokemon %>% arrange(-bmi) %>% head %>% select(generation, pokedex_number, name, bmi)
```
```{r}
ggplot(pokemon, aes(bmi)) + geom_density() + scale_x_log10()
```